
title: Stuart Macintosh(@MacintoshStuart)
name: Stuart Macintosh
email: SmTaUcM@Yahoo.co.uk
description: Stuart Macintosh's personal blog and portfolio website | Software Developer at Royal Air Force from United Kingdom.
baseurl: /
url: http://SmTaUcM.github.io
twitter: MacintoshStuart
github:  SmTaUcM
linkedin: stuart-m-86689268
facebook: SmTaUcM
hackerrank: SmTaUcM
telegram: SmTaUcM
stackoverflow: users/7793759/SmTaUcM
khanacademy: SmTaUcM
google_analytics: UA-180635106-1


# Build settings
highlighter: rouge
markdown: kramdown
permalink: /:title.html
theme: minima
plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
